### ISSUE TITLE
[Firefox Nightly 133.0a1] Sidebery now has a vertical bar that does not expand on hover

### ISSUE THREAD

**Issue by Mojavve** [dexeonify/firefox-css#3]
On the newest version of nightly there appears to be a (in theory) draggable splitter bar that borders add-on sidebars.  Not sure if this was always present or not but currently it does not expand with the rest of the sidebar using your CSS.  I usually wouldn't submit something based on a nightly update but I assume this is a new element that's here to stay.

![1729024162](https://github.com/user-attachments/assets/95a6c087-afe8-4139-9599-b3dd8dc79323)

Here's the html for the splitter:
`<splitter xmlns="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul" id="sidebar-splitter" class="chromeclass-extrachrome sidebar-splitter" resizebefore="sibling" resizeafter="none" style="order: 3;" state=""/>`

**Comment by dexeonify** [comment]
I've pushed the commits accumulated the past few weeks, hopefully it should fix your issue.
If you're using Nightly, there should be more significant issues, such as sidebar drawing behind web content (2c3fc7d9ffb90385b7a4038074724cac2ce90140) and hiding the tabs bar not working at all (633b7a7f4b5febcf1dc73a6878b3b9805e811749). The latter which warranted a rewrite from the original developer.
Otherwise, hiding the splitter should suffice (a870714034ce75e9b1c8adb369df68ac2b6cf654).

**Comment by Mojavve** [comment]
Oddly enough I haven't experienced any of these things outside of the splitter.  I've been on nightly for years.  I am on Arch Linux however, but I would be surprised if that caused differences like this.   

I appreciate the response and solutions!
